pipeline {
    agent any

    stages {
        stage('Git Clone') 
	    {
            steps 
            {
               git 'https://github.com/shivusrd/Testingbaba_maven.git'
	   
            }
        }
	    
	    stage('Clean') { 
            steps {
                 bat "mvn generate-sources"
            }
        }
       
        stage('install') 
	    {
            steps 
		{
                 
	    bat "mvn install"
		
	    
            }
		       post
            {
                success
                {
                archiveArtifacts 'target/*.jar'
                }
            
            }
			
		
        }
         stage('Clean') { 
            steps {
                 bat "mvn clean"
            }
        }
    }
}

