pipeline {
    agent any

    stages {
        stage('Git Clone') 
	    {
            steps 
            {
               git 'https://github.com/shivusrd/Testingbaba_maven.git'
	   
            }
        }
	    
	    stage('Generate-source') { 
            steps {
                 bat "mvn generate-sources"
            }
        }
       
        stage('install') 
	    {
            steps 
		{
                 
	    bat "mvn install"
	    
	    publishHTML target: [
            allowMissing: true,
            alwaysLinkToLastBuild: true,
            keepAll: true,
            reportDir: 'test-output',
            reportFiles: 'ExtentReportsTestNG.html',
            reportName: 'Extent Report'
          ]
		
	    
            }
		       post
            {
                success
                {
                archiveArtifacts 'target/*.jar'
                }
            
            }
			
		
        }
         stage('Clean') { 
            steps {
                 bat "mvn clean"
            }
        }
    }
}

