pipeline {
    agent any

    stages {
        stage('Git Clone') 
	    {
            steps 
            {
               git 'https://github.com/shivusrd/Testingbaba_maven.git'
	   
            }
        }
       
        stage('Build') 
	    {
            steps 
		{
                 
	    bat "mvn test"
		
	    
            }
			
		post
            {
                success
                {
                archiveArtifacts 'target/*.jar'
                }
            
            }
        }
         stage('Clean') { 
            steps {
                 bat "mvn clean"
            }
        }
    }
}

